# Generated by Django 4.2.6 on 2023-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_username_alter_account_alamat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alamat',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
