# Generated by Django 4.2.6 on 2023-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_book_no_of_pages_alter_book_price'),
        ('account', '0006_admin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='buku_dibeli',
            field=models.ManyToManyField(null=True, related_name='purchased', to='book.book'),
        ),
        migrations.AlterField(
            model_name='account',
            name='buku_ongoing',
            field=models.ManyToManyField(null=True, related_name='ongoing_purchase', to='book.book'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='books_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin',
            name='orders_completed',
            field=models.IntegerField(default=0),
        ),
    ]
