# Generated by Django 4.2.6 on 2023-10-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_buku_dibeli_alter_account_buku_ongoing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
