# Generated by Django 4.2.6 on 2023-10-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_username_alter_account_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
