# Generated by Django 4.2.6 on 2023-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('categories', models.TextField()),
                ('price', models.IntegerField(default=179172)),
                ('description', models.TextField(default='')),
                ('stock', models.IntegerField(default=0)),
                ('jumlah_terjual', models.IntegerField(default=0)),
            ],
        ),
    ]
