# Generated by Django 4.2.5 on 2023-11-25 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '__first__'),
        ('cart', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_info', '0002_cartofbooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOfBooks',
            new_name='CartItemBook',
        ),
    ]
