# Generated by Django 4.2.5 on 2023-11-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0003_rename_cartofbooks_cartitembook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemBook',
        ),
    ]
