# Generated by Django 4.2.6 on 2023-10-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0003_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=87253),
        ),
    ]
