# Generated by Django 4.2.6 on 2023-10-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('book_info', '0006_cart_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
    ]
