<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-28 14:21
=======
# Generated by Django 4.2.6 on 2023-10-28 15:59
>>>>>>> 754685b8679903ba70d8e65698f29bcac01627e6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0007_cart_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='jumlah_pembelian',
            field=models.IntegerField(default=1),
        ),
    ]
