# Generated by Django 4.2.6 on 2023-10-29 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_info', '0008_alter_cart_jumlah_pembelian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='jumlah_pembelian',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
