# Generated by Django 4.2.6 on 2023-10-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0009_remove_cart_jumlah_pembelian_cart_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='member',
            new_name='user',
        ),
    ]
