# Generated by Django 4.2.6 on 2023-11-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=511, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book/images')),
                ('authors', models.CharField(max_length=511, null=True)),
                ('categories', models.CharField(max_length=511, null=True)),
                ('price', models.IntegerField(default=101808)),
                ('description', models.TextField(default='')),
                ('no_of_pages', models.IntegerField(default=101)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('jumlah_terjual', models.IntegerField(default=0)),
            ],
        ),
    ]
