# Generated by Django 4.2.6 on 2023-10-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=433),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=127669),
        ),
    ]
