# Generated by Django 4.2.6 on 2023-10-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='/book/images/placeholder.png', upload_to='book/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
