# Generated by Django 4.2.6 on 2023-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20231122_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=99000),
        ),
    ]
