# Generated by Django 4.2.6 on 2023-10-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_image'),
    ]

    operations = [
    ]
