# Generated by Django 4.2.6 on 2023-10-25 06:46

from django.db import migrations, models
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books.json")


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20231025_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.RunPython(load_my_initial_data),
    ]
