# Generated by Django 4.2.6 on 2023-10-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_author_remove_book_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='jumlah_terjual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=965),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=63674),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
