<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-26 11:01
=======
# Generated by Django 4.2.6 on 2023-10-26 13:01
>>>>>>> 44a2e1a (sementara)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_description_book_jumlah_terjual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
<<<<<<< HEAD
            field=models.IntegerField(default=521),
=======
            field=models.IntegerField(default=447),
>>>>>>> 44a2e1a (sementara)
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
<<<<<<< HEAD
            field=models.IntegerField(default=52696),
=======
            field=models.IntegerField(default=199985),
>>>>>>> 44a2e1a (sementara)
        ),
    ]
