# Generated by Django 4.2.6 on 2023-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_description_book_jumlah_terjual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=447),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=199985),
        ),
    ]
