# Generated by Django 4.2.6 on 2023-10-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_book_no_of_pages_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=535),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=116416),
        ),
    ]
