# Generated by Django 4.2.6 on 2023-10-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book_image_alter_book_no_of_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=974),

        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=158590),

        ),
    ]
