<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-28 14:21
=======
# Generated by Django 4.2.6 on 2023-10-28 15:59
>>>>>>> 754685b8679903ba70d8e65698f29bcac01627e6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_alter_book_no_of_pages_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
<<<<<<< HEAD
            field=models.IntegerField(default=638),
=======
            field=models.IntegerField(default=188),
>>>>>>> 754685b8679903ba70d8e65698f29bcac01627e6
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
<<<<<<< HEAD
            field=models.IntegerField(default=90011),
=======
            field=models.IntegerField(default=196138),
>>>>>>> 754685b8679903ba70d8e65698f29bcac01627e6
        ),
    ]
