# Generated by Django 4.2.6 on 2023-10-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_alter_book_no_of_pages_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_pages',
<<<<<<< HEAD
            field=models.IntegerField(default=401),
=======
            field=models.IntegerField(default=474),
>>>>>>> 148d43d98d506634a43ee336fa7e4c31cb4ddc74
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
<<<<<<< HEAD
            field=models.IntegerField(default=196247),
=======
            field=models.IntegerField(default=130723),
>>>>>>> 148d43d98d506634a43ee336fa7e4c31cb4ddc74
        ),
    ]
